export const auth_constants = {
    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGIN_FAILURE : "LOGIN_FAILURE",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGOUT_REQUEST : "LOGOUT_REQUEST"
}

export const user_constants = {
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
    FOOD_LIST_REQUEST: "FOOD_LIST_REQUEST",
    FOOD_LIST_SUCCESS: "FOOD_LIST_SUCCESS",
    FOOD_LIST_FAILURE: "FOOD_LIST_FAILURE",
    MAKE_CHART_REQUEST: "MAKE_CHART_REQUEST",
    MAKE_CHART_SUCCESS: "MAKE_CHART_SUCCESS",
    MAKE_CHART_FAILURE: "MAKE_CHART_FAILURE",
    GET_CHART_REQUEST: "GET_CHART_REQUEST",
    GET_CHART_SUCCESS: "GET_CHART_SUCCESS",
    GET_CHART_FAILURE: "GET_CHART_FAILURE",
  };